apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: notification-namespace
  labels:
    app: notif-app
  annotations:
    description: "This is a config map for my notification application"
data:
      value: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"