apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: notification-namespace
  labels:
    app: notif-app
  annotations:
    description: "This is a deployment for my notification application"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notif-app
  template:
    metadata:
      labels:
        app: notif-app
    spec:
      containers:
      - name: my-container
        image: nishabansal19/notification-service:33-bf82db604a35bfec9f84fb6bff4aa56c35be4ce1
        ports:
        - containerPort: 8080
          env:
            - name: USERNAME
              valueFrom:
                  secretKeyRef:
                    name: notification-secret
                    key: username
            - name: PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: notification-secret
                    key: password
              envFrom:
              - configMapRef:
                    name: notification-config
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 30
          periodSeconds: 10
      restartPolicy: Always
