apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: notification-namespace
  labels:
    app: notif-app
  annotations:
    description: "This is a deployment for my notification application"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notif-app
  template:
    metadata:
      labels:
        app: notif-app
    spec:
      containers:
      - name: my-container
        image: nishabansal19/notification-service:44-48b517e6468d759921fef82990e5959082510ed6
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: password
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                    name: notification-config
                    key: value
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 30
          periodSeconds: 10
      restartPolicy: Always
