apiVersion: v1
kind: Namespace
metadata:
  name: notification-namespace
  labels:
    environment: production
    team: notif-team
  annotations:
    description: "This is a namespace for my notification application"