apiVersion: v1
kind: Role
metadata:
  name: notification-role
  namespace: notification-namespace
  labels:
    app: notif-app
  annotations:
    description: "This is a role for my notification application"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]