apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-account
  namespace: notification-namespace
  labels:
    app: notif-app
  annotations:
    description: "This is a service account for my application"
automountServiceAccountToken: true