apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification-namespace
  labels:
    app: notif-app
  annotations:
    description: "This is a service for my notification application"
spec:
  selector:
    app: notif-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP