apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Nisha396/Notification.git
    targetRevision: main
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true